services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    # environment :
    # - ALLOW_OVERRIDE=all
    # depends_on:

#  mysql:
#   image: mysql:latest
#    container_name: mysql_container
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: TBD
#      MYSQL_DATABASE: TBD
#      MYSQL_USER: TBD
#      MYSQL_PASSWORD: TBD
#    ports:
#      - "TBD:TBD"
#    volumes:
#      - ./db:/var/lib/mysql